### ISSUE TITLE
Site "Flowt.ai" listed in Workflow gallery has been sunsetted (defunct)

### ISSUE THREAD

**Issue by CCpt5** [ltdrdata/ComfyUI-Manager#1275]
Hello,

Looked at the "Workflow Gallery" tab in the manager today for the first time and tried most of the links. Noticed https://flowt.ai/ has a message saying the site has been discontinued.

Wanted to mention so you could consider removal.

![ssssss](https://github.com/user-attachments/assets/ff3365bc-11a6-471d-84a6-ba2765b935a5)

**Comment by ltdrdata** [comment]
Thank you for the notice.
