### ISSUE TITLE
Comfy UI Manager Menu - Close Button Disappeared?

### ISSUE THREAD

**Issue by CybereDrum** [ltdrdata/ComfyUI-Manager#159]
Hi 

Since the last 2 updates, Menu Manager Close Button disappeared. Have to restart ComfyUI to close the manager menu. Anyone else experiancing this? Not sure if its maybe script conflicts / interferance with other custom nodes installed. 
![ComfyUI Manager Menu - Close Button Disappeared_result](https://github.com/ltdrdata/ComfyUI-Manager/assets/60640948/415a386e-e3df-4c5e-aa6f-dfc6439f5f14)

**Comment by CybereDrum** [comment]
or am i missing something very obvious. :)

**Comment by ltdrdata** [comment]
> or am i missing something very obvious. :)

This issue arose as a result of too many items being added to the menu, unlike in the beginning. I am currently working on a layout change. For now, you can close it with the 'esc' key.

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/128333288/f607b994-c1e0-4122-89dd-7289f5db9688)

**Comment by CybereDrum** [comment]
🤦‍♂️ oh my.... im embarrassed. Thank you! Other than that wonderful work!
