### ISSUE TITLE
[ConfyUI Manager] Logging failed: [WinError 32] Another program is using this file and the process cannot access it Comfyui. log '->' comfyui. prev. log '

### ISSUE THREAD

**Issue by laidingq** [ltdrdata/ComfyUI-Manager#422]
[ConfyUI Manager] Logging failed: [WinError 32] Another program is using this file and the process cannot access it Comfyui. log '->' comfyui. prev. log '

**Comment by ltdrdata** [comment]
If ComfyUI is running elsewhere, please terminate it. Alternatively, if you have opened a file like `comfyui.prev.log` in Notepad, close it. If you're unsure where it's open, consider rebooting Windows.

**Comment by laidingq** [comment]
I didn't open any files, and even after restarting the computer, this prompt still exists. I don't know what happened

**Comment by ltdrdata** [comment]
Please test the following steps in English:

0. Reboot Computer
1. Launch and terminate ComfyUI
=> Check if an access error occurs in `comfyui.prev.log`
2. Delete the `comfyui.prev.log` file from explorer
=> Confirm if the deletion is carried out successfully
3. Launch and terminate ComfyUI
=> Verify that there are no errors in the startup message
4. Launch and terminate ComfyUI
=> Check if an access error occurs in `comfyui.prev.log`

**Comment by laidingq** [comment]
Thank you for your reply. This problem was caused by other plug-in bugs and has been fixed by its author.
