### ISSUE TITLE
ootdiffusion import failed  How to fix it

### ISSUE THREAD

**Issue by Oqkms** [ltdrdata/ComfyUI-Manager#463]
![联想截图_20240307130446](https://github.com/ltdrdata/ComfyUI-Manager/assets/161332672/56edd0a6-e228-4c93-91e0-3aab3c7c6a5c)

**Comment by YahyaKadd** [comment]
I have the Same issue !!

**Comment by ltdrdata** [comment]
You can get help from here:
https://github.com/StartHua/ComfyUI_OOTDiffusion_CXH

**Comment by YahyaKadd** [comment]
@ltdrdata this error applies to any Model i download
