### ISSUE TITLE
Every time comfyui is updated, dev torch will be uninstalled, why is there such a setting?  

### ISSUE THREAD

**Issue by junne14105** [ltdrdata/ComfyUI-Manager#475]
path=/Volumes/InvokeAI/ComfyUI / repo.is_dirty: True
Install: pip packages

## ComfyUI-Manager: EXECUTE => ['/usr/local/bin/python3', '-m', 'pip', 'install', 'torchvision']
   INFO: pip is looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
 Collecting torchvision
   Using cached torchvision-0.17.1-cp310-cp310-macosx_10_13_x86_64.whl.metadata (6.6 kB)
 Collecting torch==2.2.1 (from torchvision)
   Using cached torch-2.2.1-cp310-none-macosx_10_9_x86_64.whl.metadata (25 kB)
          Using cached torchvision-0.17.1-cp310-cp310-macosx_10_13_x86_64.whl (1.7 MB)
 Using cached torch-2.2.1-cp310-none-macosx_10_9_x86_64.whl (150.8 MB)
 Installing collected packages: torch, torchvision
   Attempting uninstall: torch
     Found existing installation: torch 2.3.0.dev20240311
     Uninstalling torch-2.3.0.dev20240311:
       Successfully uninstalled torch-2.3.0.dev20240311
   Attempting uninstall: torchvision
     Found existing installation: torchvision 0.18.0.dev20240227
     Uninstalling torchvision-0.18.0.dev20240227:
       Successfully uninstalled torchvision-0.18.0.dev20240227
[!] ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[!] torchaudio 2.2.0.dev20240227 requires torch==2.3.0.dev20240302, but you have torch 2.2.1 which is incompatible.
 Successfully installed torch-2.2.1 torchvision-0.17.1

**Comment by junne14105** [comment]
Using dev torch on the mps platform on Mac can be used very well and fix a lot of problems, and you can better use comfyui without errors

**Comment by ltdrdata** [comment]
To prevent potential issues, I will take measures to prevent forced installation of packages related to torch.

**Comment by ltdrdata** [comment]
Now this is fixed.
